-- MySQL Script generated by MySQL Workbench
-- Tue Nov 26 14:09:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_loja_oculos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_loja_oculos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_loja_oculos` DEFAULT CHARACTER SET utf8 ;
USE `db_loja_oculos` ;

-- -----------------------------------------------------
-- Table `db_loja_oculos`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_loja_oculos`.`funcionarios` (
  `id_fun` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_fun` VARCHAR(45) NOT NULL,
  `naturalidade_fun` VARCHAR(45) NOT NULL,
  `nacionalidade_fun` VARCHAR(45) NOT NULL,
  `cpf_fun` VARCHAR(45) NOT NULL,
  `rg_fun` VARCHAR(45) NOT NULL,
  `telefone_fun` VARCHAR(45) NOT NULL,
  `data_fun` VARCHAR(45) NOT NULL,
  `endereco_fun` VARCHAR(45) NOT NULL,
  `login_fun` VARCHAR(45) NOT NULL,
  `senha_fun` VARCHAR(45) NOT NULL,
  `funcao_fun` VARCHAR(45) NOT NULL,
  `status_fun` VARCHAR(45) NOT NULL DEFAULT 'ATIVO',
  PRIMARY KEY (`id_fun`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_loja_oculos`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_loja_oculos`.`vendas` (
  `id_ven` INT(11) NOT NULL AUTO_INCREMENT,
  `data_ven` VARCHAR(45) NOT NULL,
  `desconto_ven` VARCHAR(45) NOT NULL,
  `funcionarios_id_fun` INT(11) NOT NULL,
  PRIMARY KEY (`id_ven`),
  INDEX `fk_vendas_funcionarios_idx` (`funcionarios_id_fun` ASC),
  CONSTRAINT `fk_vendas_funcionarios`
    FOREIGN KEY (`funcionarios_id_fun`)
    REFERENCES `db_loja_oculos`.`funcionarios` (`id_fun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_loja_oculos`.`oculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_loja_oculos`.`oculos` (
  `id_ocls` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_ocls` VARCHAR(45) NOT NULL,
  `marca_ocls` VARCHAR(45) NOT NULL,
  `tipo_ocls` VARCHAR(45) NOT NULL,
  `modelo_ocls` VARCHAR(45) NOT NULL,
  `cor_armacao_ocls` VARCHAR(45) NOT NULL,
  `material_armacao_ocls` VARCHAR(45) NOT NULL,
  `cor_lente_ocls` VARCHAR(45) NOT NULL,
  `tipo_lente_ocls` VARCHAR(45) NOT NULL,
  `preco_ocls` DECIMAL(10,2) NOT NULL,
  `imagem_ocls` VARCHAR(255) NOT NULL,
  `fila_compra_ocls` VARCHAR(1) NOT NULL DEFAULT 'N',
  `vendas_id_ven` INT(11) NULL,
  PRIMARY KEY (`id_ocls`),
  INDEX `fk_oculos_vendas1_idx` (`vendas_id_ven` ASC),
  CONSTRAINT `fk_oculos_vendas1`
    FOREIGN KEY (`vendas_id_ven`)
    REFERENCES `db_loja_oculos`.`vendas` (`id_ven`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

drop schema db_loja_oculos;